### ISSUE TITLE
引入sdk后，安卓初始化一直不成功，ios没事

### ISSUE THREAD

**Issue by CrankGentleman** [finogeeks/finclip-flutter-demo#3]
通过控制台查看

FinAppClient init isLicensed : false

安卓的程序packageid和后台填写的一致，ak和sk也填写的是正确的，ios可以初始化成功，但安卓死活不行，烦死个人了

**Comment by Limitlesser** [comment]
android应用对应的唯一标识是applicationId，确认下app的applicationId是否与后台配置的一致呢
